Bugfixes in startup script and server

diff --git a/server/server b/server/server
--- a/server/server
+++ b/server/server
@@ -28,21 +28,21 @@ start_server() {
     echo "Rebuilding the client? (y/n)"
     read -r rebuild
     if [ "$rebuild" = "y" ]; then
-        echo "Running npm install in the client directory..."
-        cd ../client && npm install
+        echo "Running npm run build in the client directory..."
+        cd ../client && npm run build
         if [ $? -ne 0 ]; then
-            echo "Failed to run npm install in the client directory. Exiting."
+            echo "Failed to run npm run build in the client directory. Exiting."
             exit 1
         fi
         cd ../server || exit
     fi
 
     # Start the server with the provided arguments or defaults
-    echo "Starting the server with environment ${1:-prod} on port ${2:-443}..."
-    nohup sudo -S node server.js "$@" > output.log 2>&1 &
+    echo "Starting the server..."
+    nohup node server.js "$@" > output.log 2>&1 &
     # Check if the server started successfully
     sleep 5  # Wait for a few seconds to let the server start
-    if pgrep -f "node server/server.js" > /dev/null; then
+    if pgrep -f "node server.js" > /dev/null; then
         echo "Server started successfully."
         echo "Output is redirected to output.log."
     else
@@ -50,7 +50,7 @@ start_server() {
         echo "Please enter your password if prompted."
         sudo nohup node server.js "$@" > output.log 2>&1 &
         sleep 5  # Wait for a few seconds to let the server start
-        if pgrep -f "node server/server.js" > /dev/null; then
+        if pgrep -f "node server.js" > /dev/null; then
             echo "Server started successfully with sudo privileges."
             echo "Output is redirected to output.log."
         else
@@ -62,11 +62,17 @@ start_server() {
 stop_server() {
     echo "Stopping the server..."
 
-    sudo pkill -f node
+    pkill -f node
 
     if [ $? -ne 0 ]; then
-        echo "Failed to stop the server. Are you sure it's running?"
-        exit 1
+        echo "Failed to stop the server. Retry with sudo privileges..."
+        echo "Please enter your password if prompted."
+        sudo pkill -f node
+        if [ $? -ne 0 ]; then
+            echo "Failed to stop the server. Check output.log for more information."
+        else
+            echo "Server stopped successfully with sudo privileges."
+        fi
     fi
     echo "Server stopped successfully."
 }
